### ISSUE TITLE
org.sputnikdev.bluetooth.manager.NotReadyException: Could not power adapter

### ISSUE THREAD

**Issue by vkolotov** [sputnikdev/eclipse-smarthome-bluetooth-binding#10]
@Simsal:

I tried installing your binding, getting following errors:
```
2018-01-09 21:21:08.565 [WARN ] [ace.internal.BindingExtensionHandler] - Installed bundle, but failed to start it: Could not resolve module: org.sputnikdev.org.eclipse.smarthome.binding.bluetooth.transport.bluegiga [239]
      Unresolved requirement: Import-Package: org.sputnikdev.bluetooth

    2018-01-09 21:21:10.341 [WARN ] [ace.internal.BindingExtensionHandler] - Installed bundle, but failed to start it: Could not resolve module: org.sputnikdev.org.eclipse.smarthome.binding.bluetooth.transport.tinyb [240]
      Unresolved requirement: Import-Package: org.sputnikdev.bluetooth

    2018-01-09 21:21:30.395 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "DFU Control Point" does not have either Value or Fields tags, therefore reading the such characteristic will not be possible.
    2018-01-09 21:21:30.425 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "DFU Packet" does not have either Value or Fields tags, therefore reading the such characteristic will not be possible.
    2018-01-09 21:21:30.965 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "Bond Management Control Point" is not valid neither for read nor for write operation due to unfulfilled requirements: read ([Conditional]) write ([Conditional]).
    2018-01-09 21:21:31.117 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "CGM Measurement" is not valid neither for read nor for write operation due to unfulfilled requirements: read ([C3]) write ([C3, C1, C2]).
    2018-01-09 21:21:31.136 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "CGM Session Run Time" is not valid neither for read nor for write operation due to unfulfilled requirements: read ([C1]) write ([C1]).
    2018-01-09 21:21:31.155 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "CGM Session Start Time" is not valid neither for read nor for write operation due to unfulfilled requirements: read ([C1]) write ([C1]).
    2018-01-09 21:21:31.195 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "CGM Specific Ops Control Point" is not valid neither for read nor for write operation due to unfulfilled requirements: read ([C1]) write ([C1]).
    2018-01-09 21:21:31.213 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "CGM Status" is not valid neither for read nor for write operation due to unfulfilled requirements: read ([C1]) write ([C1]).
    2018-01-09 21:21:31.302 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "Cycling Power Control Point" is not valid neither for read nor for write operation due to unfulfilled requirements: read ([Optional, C1, C2]) write ([Optional, C1, C2]).
    2018-01-09 21:21:31.381 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "Cycling Power Measurement" is not valid neither for read nor for write operation due to unfulfilled requirements: read ([C3, C4, C5, Optional, C1, C2]) write ([C3, C4, C5, Optional, C1, C2]).
    2018-01-09 21:21:31.416 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "Cycling Power Vector" is not valid neither for read nor for write operation due to unfulfilled requirements: read ([Optional, C1, C2]) write ([Optional, C1, C2]).
    2018-01-09 21:21:31.535 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "Descriptor Value Changed" does not have either Value or Fields tags, therefore reading the such characteristic will not be possible.
    2018-01-09 21:21:32.333 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "LN Control Point" is not valid neither for read nor for write operation due to unfulfilled requirements: read ([Optional, C1, C2]) write ([Optional, C1, C2]).
    2018-01-09 21:21:32.427 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "Location and Speed Characteristic" is not valid neither for read nor for write operation due to unfulfilled requirements: read ([Optional, C1]) write ([Optional, C1]).
    2018-01-09 21:21:32.582 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "Navigation" is not valid neither for read nor for write operation due to unfulfilled requirements: read ([Optional]) write ([Optional]).
    2018-01-09 21:21:32.612 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "Object Action Control Point" does not have either Value or Fields tags, therefore reading the such characteristic will not be possible.
    2018-01-09 21:21:32.626 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "Object Changed" does not have either Value or Fields tags, therefore reading the such characteristic will not be possible.
    2018-01-09 21:21:32.681 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "Object List Control Point" does not have either Value or Fields tags, therefore reading the such characteristic will not be possible.
    2018-01-09 21:21:32.693 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "Object List Filter" does not have either Value or Fields tags, therefore reading the such characteristic will not be possible.
    2018-01-09 21:21:32.721 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "Object Properties" does not have either Value or Fields tags, therefore reading the such characteristic will not be possible.
    2018-01-09 21:21:32.762 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "OTS Feature" does not have either Value or Fields tags, therefore reading the such characteristic will not be possible.
    2018-01-09 21:21:32.919 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "Position Quality" is not valid neither for read nor for write operation due to unfulfilled requirements: read ([Optional]) write ([Optional]).
    2018-01-09 21:21:33.127 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "SC Control Point" is not valid neither for read nor for write operation due to unfulfilled requirements: read ([C3, C1, C2]) write ([C3, C1, C2]).
    2018-01-09 21:21:33.266 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "TDS Control Point" does not have either Value or Fields tags, therefore reading the such characteristic will not be possible.
    2018-01-09 21:21:33.570 [WARN ] [pec.BluetoothGattSpecificationReader] - Characteristic "User Control Point" does not have either Value or Fields tags, therefore reading the such characteristic will not be possible.
    2018-01-09 21:21:37.052 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'bluetooth:adapter:B827EB9DF87C' to inbox.
    2018-01-09 21:22:07.907 [WARN ] [.core.thing.binding.BaseThingHandler] - BaseThingHandler.initialize() will be removed soon, ThingStatus can be set manually via updateStatus(ThingStatus.ONLINE)
    2018-01-09 21:22:08.039 [WARN ] [impl.AbstractBluetoothObjectGovernor] - Could not update governor state.
    org.sputnikdev.bluetooth.manager.NotReadyException: Could not power adapter
            at org.sputnikdev.bluetooth.manager.impl.AdapterGovernorImpl.updatePowered(AdapterGovernorImpl.java:218) ~[?:?]
            at org.sputnikdev.bluetooth.manager.impl.AdapterGovernorImpl.update(AdapterGovernorImpl.java:65) ~[?:?]
            at org.sputnikdev.bluetooth.manager.impl.AdapterGovernorImpl.update(AdapterGovernorImpl.java:42) ~[?:?]
            at org.sputnikdev.bluetooth.manager.impl.AbstractBluetoothObjectGovernor.update(AbstractBluetoothObjectGovernor.java:160) ~[?:?]
            at org.sputnikdev.bluetooth.manager.impl.AbstractBluetoothObjectGovernor.init(AbstractBluetoothObjectGovernor.java:150) ~[?:?]
at org.sputnikdev.bluetooth.manager.impl.BluetoothManagerImpl.lambda$null$4(BluetoothManagerImpl.java:236) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

```
sudo systemctl status bluetooth
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled)
   Active: active (running) since Tue 2018-01-09 21:19:58 CET; 4min 19s ago
     Docs: man:bluetoothd(8)
 Main PID: 6856 (bluetoothd)
   Status: "Running"
   CGroup: /system.slice/bluetooth.service
           └─6856 /usr/libexec/bluetooth/bluetoothd

Jan 09 21:19:58 openHABianPi bluetoothd[6856]: Bluetooth daemon 5.47
Jan 09 21:19:58 openHABianPi systemd[1]: Started Bluetooth service.
Jan 09 21:19:58 openHABianPi bluetoothd[6856]: Starting SDP server
Jan 09 21:19:58 openHABianPi bluetoothd[6856]: Bluetooth management interface 1.14 initialized
```

**Comment by vkolotov** [comment]
The very first WARNING messages are normal, that’s when you have installed transport bundles first without installing the Bluetooth binding. So this should de ignored.

The second part is more interesting:
```
org.sputnikdev.bluetooth.manager.NotReadyException: Could not power adapter
```
Looks like the binding cannot power up your adapter. Can you please let me know more info about your set up. What adapter you have? Can you also please run the “bluetoothctl” utility and see if that utility can power up your adapter? Something like that:
```
pi@raspberrypi:~ $ bluetoothctl 
[blahblah]# list
Controller XX:XX:XX:XX:XX:XX AZIO - Entrance hall [default]
Controller XX:XX:XX:XX:XX:XX AZIO - Living area 
Controller XX:XX:XX:XX:XX:XX Internal Adapter - Kitchen 

[blahblah]# select XX:XX:XX:XX:XX:XX -- your adapter MAC here from the result above

[blahblah]# show
Controller XX:XX:XX:XX:XX:XX
	Name: BlueZ 5.47
	Alias: Internal Adapter - Kitchen
	Class: 0x00000000
	Powered: yes
	Discoverable: no
	Pairable: yes
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v1D6Bp0246d052F
	Discovering: yes
```

Notice this:
```
Powered: yes
```
Is it “no” for you?

If so, try to power it up:
```
[blahblah]# power on
Changing power on succeeded
```

**Comment by vkolotov** [comment]
@Simon:

Yesterday everything seemed to work smothly after few seconds. Today my log gets flooded with the notReadyException
About every 20 seconds i get the error message
```
2018-01-10 20:31:37.613 [WARN ] [impl.AbstractBluetoothObjectGovernor] - Could not update governor state.
org.sputnikdev.bluetooth.manager.NotReadyException: Could not power adapter
        at org.sputnikdev.bluetooth.manager.impl.AdapterGovernorImpl.updatePowered(AdapterGovernorImpl.java:218) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.AdapterGovernorImpl.update(AdapterGovernorImpl.java:65) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.AdapterGovernorImpl.update(AdapterGovernorImpl.java:42) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.AbstractBluetoothObjectGovernor.update(AbstractBluetoothObjectGovernor.java:160) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.BluetoothManagerImpl.update(BluetoothManagerImpl.java:471) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.BluetoothManagerImpl.lambda$scheduleGovernor$19(BluetoothManagerImpl.java:608) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?] 

2018-01-10 20:39:08.381 [WARN ] [impl.AbstractBluetoothObjectGovernor] - Could not update governor state.
tinyb.BluetoothException: Timeout was reached
        at tinyb.BluetoothDevice.connect(Native Method) ~[?:?]
        at org.sputnikdev.bluetooth.manager.transport.tinyb.TinyBDevice.connect(TinyBDevice.java:67) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.DeviceGovernorImpl.updateConnected(DeviceGovernorImpl.java:557) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.DeviceGovernorImpl.update(DeviceGovernorImpl.java:109) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.DeviceGovernorImpl.update(DeviceGovernorImpl.java:57) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.AbstractBluetoothObjectGovernor.update(AbstractBluetoothObjectGovernor.java:160) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.BluetoothManagerImpl.update(BluetoothManagerImpl.java:471) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.BluetoothManagerImpl.lambda$scheduleGovernor$19(BluetoothManagerImpl.java:608) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2018-01-10 20:39:18.558 [WARN ] [impl.AbstractBluetoothObjectGovernor] - Could not update governor state.
tinyb.BluetoothException: GDBus.Error:org.bluez.Error.Failed: Operation already in progress
        at tinyb.BluetoothDevice.connect(Native Method) ~[?:?]
        at org.sputnikdev.bluetooth.manager.transport.tinyb.TinyBDevice.connect(TinyBDevice.java:67) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.DeviceGovernorImpl.updateConnected(DeviceGovernorImpl.java:557) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.DeviceGovernorImpl.update(DeviceGovernorImpl.java:109) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.DeviceGovernorImpl.update(DeviceGovernorImpl.java:57) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.AbstractBluetoothObjectGovernor.update(AbstractBluetoothObjectGovernor.java:160) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.BluetoothManagerImpl.update(BluetoothManagerImpl.java:471) ~[?:?]
        at org.sputnikdev.bluetooth.manager.impl.BluetoothManagerImpl.lambda$scheduleGovernor$19(BluetoothManagerImpl.java:608) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```
The error messages with “Could not power adapter” “Timeout reached” and “operation in progress” are alternating

```
Controller:
Controller B8:27:EB:9D:F8:7C BlueZ 5.47 [default]

[bluetooth]# show

Controller B8:27:EB:9D:F8:7C
	Name: BlueZ 5.47
	Alias: BlueZ 5.47
	Class: 0x00000000
	Powered: yes
	Discoverable: no
	Pairable: yes
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v1D6Bp0246d052F
	Discovering: yes
```

Other Setup:
Rpi3 with openhabian ( latest snapshot builds)

**Comment by vkolotov** [comment]
Hi @Simsal, thank you for reporting this.

Let’s start from the beginning. Before yesterday you reported “Could not power adapter” error, how did you resolve this? Did you use bluetooth “bluetoothctl” tool to power up your adapter as I suggested earlier?

The errors “Timeout was reached” and “Operation already in progress” show that you have managed to power up the adapter and your are trying to connect to a device. What device is it? How far is it from the adapter? Just bear in mind that, if your device is too far from the adapter, the connection might be unstable. Just in general, if RSSI value is greater than -80 (meaning actually lesser, e.g. -81, -82 etc), then it is not recommended to connect to this device as the connection will be unstable. This is probably should be limited by the Bluetooth binding… it is probably a good idea. What do you guys think?

We could add a global binding setting, like a “RSSI connection threshold” that would prevent connection attempts if the device is too far.

Pease also note that the Binding can be too talkative for the initial phase of betta testing, this is done on purpose for troubleshooting. For example, the errors “Timeout was reached” and “Operation already in progress” will be probably hidden in future.

**Comment by vkolotov** [comment]
@sozkara:
> 
I’m getting the same errors with @Simsal. When i turn off discovery, i can’t turn it back on. The log entry below is repeating.

```
01:34:36.047 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'bluetooth:adapter:B827EBF41C67' changed from OFFLINE to ONLINE
01:34:36.368 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'bluetooth:adapter:B827EBF41C67' changed from ONLINE to OFFLINE
01:34:41.404 [WARN ] [.impl.AbstractBluetoothObjectGovernor] - Could not update governor state.
org.sputnikdev.bluetooth.manager.NotReadyException: Could not power adapter
	at org.sputnikdev.bluetooth.manager.impl.AdapterGovernorImpl.updatePowered(AdapterGovernorImpl.java:218) ~[?:?]
	at org.sputnikdev.bluetooth.manager.impl.AdapterGovernorImpl.update(AdapterGovernorImpl.java:65) ~[?:?]
	at org.sputnikdev.bluetooth.manager.impl.AdapterGovernorImpl.update(AdapterGovernorImpl.java:42) ~[?:?]
	at org.sputnikdev.bluetooth.manager.impl.AbstractBluetoothObjectGovernor.update(AbstractBluetoothObjectGovernor.java:160) ~[?:?]
	at org.sputnikdev.bluetooth.manager.impl.BluetoothManagerImpl.update(BluetoothManagerImpl.java:471) ~[?:?]
	at org.sputnikdev.bluetooth.manager.impl.BluetoothManagerImpl.lambda$scheduleGovernor$19(BluetoothManagerImpl.java:608) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

```
[bluetooth]# show
Controller B8:27:EB:F4:1C:67 (public)
	Name: raspi-zero
	Alias: raspi-zero
	Class: 0x00000000
	Powered: yes
	Discoverable: no
	Pairable: yes
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v1D6Bp0246d0530
	Discovering: no
```
This is using bluez 5.48 on raspberry pi zero wireless…

**Comment by vkolotov** [comment]
Thanks for your report @sozkara, could you also please let me know what OS you are using and what version of OH? I’ll try to install that thing on raspberry pi zero and see how it goes. Although I’m not sure if it is a good idea to use PI Zero as it is really low spec board…

It also might be due to the new version of Bluez, from what I can see in the release notes, they have implemented another bunch of “improvements and bugfixes” :smile:. My current version of Bluez is 5.47, that’s what I use for testing as it must be more stable and included by default in major linux distributions.

**Comment by vkolotov** [comment]
I’ve tried to install the new Bluez version - v5.48. A lot of things broken. I also had “Could not power adapter” as well. But the worst thing is - not all GATT services now getting resolved, for example battery service (https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.service.battery_service.xml) does not get resolved any more. Who know what else wrong… I do not recommend to upgrade to 5.48 as obviously there are some changes that TinyB library does not support yet. I’ll create some bug reports for both Bluez and TinyB projects, will see how it goes.

So if you are on Bluez 5.48, please downgrade it to 5.47 using this [instructions](https://github.com/sputnikdev/bluetooth-manager-tinyb#prerequisites)

**Comment by vkolotov** [comment]
@sozkara

> Hi @vkolotov ,
> I’m running OH 2.3.0 snaphot Version: 2.3.0~20180107033436-1 on raspbian jessie. uname shows me this line:
> 
> Linux raspi-zero 4.9.75+ #1074 Mon Jan 8 13:59:41 GMT 2018 armv6l GNU/Linux
> Although it may seem underpowered, rPi Zero Wireless gets the job done with low power requirements. :slight_smile: It may be slow to start OH2 but after that, it’s really ok.
> 
> I’ll post back here once i compile the 5.47 version and use it. Though i have to mention that i had problems with 5.43 version also.
