### ISSUE TITLE
Unable to connect to a device by using its public address when using BlueGiga transport

### ISSUE THREAD

**Issue by vkolotov** [sputnikdev/eclipse-smarthome-bluetooth-binding#28]
It seem to me that if a bluetooth device advertises its address as public, BlueGiga adapter/transport is unable to connect to that device failing with a timeout error.

```
12:01:55.550  WARN   Could not update governor state.
org.sputnikdev.bluetooth.manager.transport.bluegiga.BluegigaException: Could not receive expected event
	at org.sputnikdev.bluetooth.manager.transport.bluegiga.BluegigaHandler.syncCall(BluegigaHandler.java:332)
	at org.sputnikdev.bluetooth.manager.transport.bluegiga.BluegigaHandler.connect(BluegigaHandler.java:185)
	at org.sputnikdev.bluetooth.manager.transport.bluegiga.BluegigaDevice.establishConnection(BluegigaDevice.java:302)
	at org.sputnikdev.bluetooth.manager.transport.bluegiga.BluegigaDevice.lambda$connect$0(BluegigaDevice.java:112)
	at org.sputnikdev.bluetooth.manager.transport.bluegiga.BluegigaHandler.runInSynchronizedContext(BluegigaHandler.java:180)
	at org.sputnikdev.bluetooth.manager.transport.bluegiga.BluegigaDevice.connect(BluegigaDevice.java:101)
	at org.sputnikdev.bluetooth.manager.impl.DeviceGovernorImpl.updateConnected(DeviceGovernorImpl.java:558)
	at org.sputnikdev.bluetooth.manager.impl.DeviceGovernorImpl.update(DeviceGovernorImpl.java:109)
	at org.sputnikdev.bluetooth.manager.impl.DeviceGovernorImpl.update(DeviceGovernorImpl.java:57)
	at org.sputnikdev.bluetooth.manager.impl.AbstractBluetoothObjectGovernor.update(AbstractBluetoothObjectGovernor.java:158)
	at org.sputnikdev.bluetooth.manager.impl.BluetoothManagerImpl.update(BluetoothManagerImpl.java:527)
	at org.sputnikdev.bluetooth.manager.impl.BluetoothManagerImpl.lambda$scheduleGovernor$19(BluetoothManagerImpl.java:657)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vkolotov** [comment]
Fixed in v1.1
